version: 2

models:
  - name: dim_answer_details
    columns:
      - name: srgt_key_answers
        tests:
          - unique
          - not_null
      - name: answer_id
        tests:
          - unique
          - not_null

  - name: dim_dates
    columns:
      - name: date_actual
        tests:
          - unique
          - not_null

  - name: dim_users
    columns:
      - name: sk_dim_users
        tests:
          - unique
          - not_null
      - name: user_id
        tests:
          - unique
          - not_null

  - name: dim_question_details
    columns:
      - name: sk_dim_question_details
        tests:
          - unique
          - not_null
      - name: question_id
        tests:
          - unique
          - not_null

  - name: fct_questions
    columns:
      - name: id
        tests:
          - unique
          - not_null